{{- if hasKey .Values "ingress_hosts" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  rules:
    {{- .Values.ingress_hosts | toYaml | nindent 4 }}
{{- end }}